@startuml "Package contenant tous les packages"

namespace zoot {
   ' Includes
   !include code_generation.puml
   !include exceptions.puml
   !include analyse.puml
   !include arbre.puml
   !include tds.puml
   ' Classes
   class Zoot {
      + Zoot(String nomFichier)
      + static void main(String[] args)
   }
   ' Relations entre les classes
   Zoot ..> zoot.analyse.AnalyseurLexical
   Zoot ..> zoot.analyse.AnalyseurSyntaxique
   Zoot ..> zoot.arbre.ArbreAbstrait
}

hide empty member
' hide zoot.analyse
' hide zoot.exceptions

@enduml