@startuml "Package code_generation"

namespace zoot.code_generation {
    ' Includes
    ' Classes
    enum Registre{
        .. Identifiants ..
        POINTEUR_PILE
        POINTEUR_DEBUT_ZONE_PILE
        STOCKAGE_TEMPORAIRE
        STOCKAGE_RESULTAT
        .. Définition Objet ..
        + String valeur
        - Registre(String valeur)
    }

    class MipsGenerator << (S,#FF7700) >> {
        - MipsGenerator()
        + MipsGenerator getInstance()
        .. Opérations ALU ..
        + String chargementImmediat(String registre, String valeur)
        + String chargementAdresse(String registre, String valeur)
        + String copieRegistreRegistre(String registreSource, String registreDestination)
        + String affectation(String nom, Expression expression)
        .. Gestion de la pile ..
        + String reserverOctetsPile(int nbOctets)
        + String libererOctetsPile(int nbOctets)
        .. Gestion de l'affichage ..
        + String afficherCaractere(String valeur)
        + String afficherEntierRegistre(String registre)
        + String afficherBooleenRegistre(String registre)
        + String afficherRetourLigne()
        .. Gestion du programme ..
        + String enteteProgramme()
        + String finProgramme()
    }

    ' Relations entre les classes
    MipsGenerator -right-"1" MipsGenerator : statique
    MipsGenerator .left.> Registre

}
@enduml