@startuml "Package exceptions"

namespace zoot.exceptions {
    ' Includes
    ' Classes
    class GestionnaireExceptionsSemantiques << (S,#FF7700) >> {
    - GestionnaireExceptionsSemantiques()
    + GestionnaireExceptionsSemantiques getInstance()
    + void ajouter(AnalyseSemantiqueException e)
    + int getNbExceptions()
    + String getMessagesExceptions()
  }

    abstract class AnalyseException {
        # AnalyseException(String m)
    }

    class AnalyseLexicaleException {
        + AnalyseLexicaleException(int ligne, int colonne, String m)
    }

    class AnalyseSyntaxiqueException {
        + AnalyseSyntaxiqueException(String m)
    }

    class AnalyseSemantiqueException {
        + AnalyseSemantiqueException(String m)
    }

    ' Relations entre les classes
    AnalyseException -up-|> RuntimeException
    AnalyseLexicaleException -up-|> AnalyseException
    AnalyseSyntaxiqueException -up-|> AnalyseException
    AnalyseSemantiqueException -up-|> AnalyseException
    GestionnaireExceptionsSemantiques -down-"*" AnalyseSemantiqueException
}
@enduml