@startuml "Package expressions"
namespace zoot.arbre.expressions {
    ' Includes
    ' Classes
    abstract class Expression {
        # Expression(int n)
        + Type getType()
    }

    abstract class Constante {
        # String cste
        # Constante(String texte, int n)
        + String toString()
    }

    class ConstanteEntiere {
        + ConstanteEntiere(String texte, int n)
        + Type getType()
        + String toMIPS()
    }

    class ConstanteBooleene {
        + ConstanteBooleene(String texte, int n)
        + Type getType()
        + String toMIPS()

    }

    abstract class Identifiable {
        + Identifiable(Entree e, int n)
        + Type getType()
        + void verifier()
    }

    class Variable {
        - int deplacement
        - int niveauImbrication
        + Variable(EntreeVariable e, int n)
        + void setDeplacement(int deplacement)
        + int getDeplacement()
        + void setNiveauImbrication(int niveauImbrication)
        + int getNiveauImbrication()
        + void verifier()
        + String toMIPS()
    }

    class AppelFonction {
        - int niveauImbrication
        - int tailleDisplay
        - int tailleZoneParametres
        - String etiquette
        + AppelFonction(EntreeFonction e, int n)
        + int getTailleZoneParametres()
        + void setTailleDisplay(int tailleDisplay)
        + int getTailleDisplay()
        + void setNiveauImbrication(int niveauImbrication)
        + int getNiveauImbrication()
        + void setEtiquette(String etiquette)
        + String getEtiquette()
        + void verifier()
        + String toMIPS()
    }
    ' Relations entre les classes
    Expression -up-|> zoot.arbre.ArbreAbstrait
    Constante -up-|> Expression
    ConstanteEntiere -up-|> Constante
    ConstanteBooleene -right-|> Constante
    Identifiable *-up- zoot.tds.entrees.Entree
    Identifiable *-up- zoot.tds.symboles.Symbole
    Identifiable -left-|> Expression
    Variable -up-|> Identifiable
    AppelFonction -left-|> Identifiable
}
@enduml