@startuml "Package expressions"
namespace zoot.arbre.expressions {
    ' Includes
    ' Classes
    abstract class Expression {
        # Expression(int n)
        + Type getType() '
    }

    abstract class Constante {
        # String cste
        # Constante(String texte, int n)
        + void verifier()
        + String toString()
    }

    class ConstanteEntiere {
        + ConstanteEntiere(String texte, int n)
        + Type getType() '
        + String toMIPS()
    }

    class ConstanteBooleene {
        + ConstanteBooleene(String texte, int n) '
        + Type getType() '
        + String toMIPS() '

    }

    abstract class Identifiable {
        + Identifiable(Entree e, int n) '
    }

    class Variable {
        - int deplacement
        + Variable(EntreeVariable e, int n) '
        + void setDeplacement(int deplacement) '
        + void verifier() '
        + String toMIPS() '
    }
    ' Relations entre les classes
    Expression -up-|> zoot.arbre.ArbreAbstrait
    Constante -up-|> Expression
    ConstanteEntiere -up-|> Constante
    ConstanteBooleene -right-|> Constante
    Identifiable -right-|> Expression
    Variable -up-|> Identifiable
    Variable --"1" zoot.tds.SymboleVariable
    Variable *-- zoot.tds.EntreeVariable
}
@enduml