@startuml "Package instructions"

namespace zoot.arbre.instructions {
    ' Includes
    ' Classes
    class Ecrire {
        + Ecrire (Expression e, int n)
        + void verifier()
        + String toMIPS()
        + void sAjouter(ConteneurDInstructions c)
    }

    class Affectation {
        + Affectation (Variable v, Expression e, int n)
        + void verifier()
        + String toMIPS()
        + void sAjouter(ConteneurDInstructions c)
    }

    class Retourne {
        - int tailleZoneVariables
        + Retourne(Expression e, int n)
        + void verifier()
        + String toMIPS()
        + Optional<Type> getType()
        + void sAjouter(ConteneurDInstructions c)
        + void setTailleZoneVariables(int tailleZoneVariables)
        + int getTailleZoneVariables()
    }

    abstract class Instruction {
        # Instruction(int n)
        + abstract void sAjouter(ConteneurDInstructions c)
    }
    
    ' Relations entre les classes
    Ecrire -up-|> Instruction
    Ecrire *-right- zoot.arbre.expressions.Expression
    Instruction -up-|> zoot.arbre.ArbreAbstrait
    Affectation -right-|> Instruction
    Affectation *-- zoot.arbre.expressions.Variable
    Affectation *-down- zoot.arbre.expressions.Expression
    Retourne *-- zoot.arbre.expressions.Expression
    Retourne --|> Instruction
}

@enduml