@startuml "tds"

namespace zoot.tds {
  ' Includes

  ' Classes
  class TDS << (S,#FF7700) >> {
    - TDS()
    + TDS getInstance()
    + void ajouter(Entree entree, Symbole symbole)
    + Symbole identifier(Entree entree)
    + int getTailleZoneVariables()
  }

  abstract class Entree {
    # String identifiant
    + Entree(String identifiant)
    + String getIdentifiant()
    + boolean equals(Object objetAComparer)
  }

  class EntreeVariable {
    + EntreeVariable(String identifiant)
    + boolean equals(Object objetAComparer)
  }

  abstract class Symbole {
    + Symbole(Type type)
    + Type getType()
  }

  class SymboleVariable {
    - int deplacement
    + SymboleVariable(Type type)
    + int getDeplacement()
    + int setDeplacement(int deplacement)
    + boolean equals(Object objetAComparer)
  }

  enum Type {
    ENTIER
    BOOLEEN
  }

  ' Relations entre les classes
  EntreeVariable --|> Entree
  SymboleVariable --|> Symbole
  Symbole *-- Type
  TDS --"1" TDS : statique
  TDS --"*" Entree
  TDS --"*" Symbole
  TDS ..> zoot.exceptions.GestionnaireExceptionsSemantiques
}

@enduml
